#!/usr/bin/with-contenv bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8080" \
        s6-setuidgid abc java \
            -jar \
            -Dconfig.file=/config/ha-bridge.config \
            -Dexec.garden=/config/scripts \
            -Dsecurity.key="$SEC_KEY" \
            /app/ha-bridge.jar
