#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
    /config/scripts \

# copy config file
if [[ ! -e /config/ha-bridge.config ]]; then
    cp /defaults/ha-bridge.config /config/ha-bridge.config
fi

# set permissions
lsiown -R abc:abc \
    /config
